<fieldset>
 <legend>Các trường dữ liệu</legend>
 <p>
 <label>Bạn đọc</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tất cả</option>
 <option value="aud:a">Vị thành niên</option>
 <option value="aud:b">Sách cho trẻ từ(0-5)</option>
 <option value="aud:c">Sách cho trẻ từ (5-8)</option>
 <option value="aud:d">Sách cho trẻ từ(9-14)</option>
 <option value="aud:e">Vị thành niên</option>
 <option value="aud:k">Sách cho người lớn</option>
 <option value="aud:m">Sách cho người lớn nói chung</option>
 <option value="aud:u">Không biết</option>
 </select>
 </p>
 <p>
 <label>Mô tả vật lý</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tất cả</option>
 <option value="Material-type:r">In thường</option>
 <option value="Material-type:d">In khổ lớn</option>
 <option value="Material-type:e">Định dạng báo</option>
 <option value="Material-type:f">Sách chữ nổi Braille và bản khắc</option>
 <option value="Material-type:g">micro phim</option>
 <option value="Material-type:h">Bản thảo viết tay</option>
 <option value="Material-type:i">Tài liệu nghe nhìn</option>
 <option value="Material-type:j">mini-print</option>
 <option value="Material-type:s">Nguồn sách điện tử</option>
 <option value="Material-type:t">micro phim</option>
 <option value="Material-type:z">Loại khác</option>
 </select>
 </p>
 <p>
 <label>Phân loại sách</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Tất cả</option>
 <option value="Literature-Code:a">Viễn tưởng</option>
 <option value="Literature-Code:b">Kịch</option>
 <option value="Literature-Code:c">Tiểu luận</option>
 <option value="Literature-Code:d">Tryện cười</option>
 <option value="Literature-Code:e">Văn học</option>
 <option value="Literature-Code:f">Truyện ngắn</option>
 <option value="Literature-Code:g">Thơ</option>
 <option value="Literature-Code:h">Diễn văn, biện luận</option>
 <option value="Literature-Code:i">Thể loại nhạc kịch</option>
 <option value="Literature-Code:y">Các thể loại khác</option>
 <option value="Literature-Code:z">Các thể loại hình thức văn học</option>
 </select>
 </p>
 <p>
 <label>Hồi ký, tiểu sử</label>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Biography-code:y">Không phải tiểu sử</option>
 <option value="Biography-code:a">Tự truyện</option>
 <option value="Biography-code:b">Tiểu sử cá nhân</option>
 <option value="Biography-code:c">Bộ tiểu sử</option>
 <option value="Biography-code:d">Dữ liệu tiểu sử</option>
 </select>
 </p>
 <p>
 <label>Minh họa</label>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Illustration-Code:a">Minh họa</option>
 <option value="Illustration-Code:b">Bản đồ</option>
 <option value="Illustration-Code:c">Chân dung</option>
 <option value="Illustration-Code:d">Biểu đồ</option>
 <option value="Illustration-Code:e">Sơ đồ</option>
 <option value="Illustration-Code:f">Điêu khắc</option>
 <option value="Illustration-Code:g">Âm nhạc</option>
 <option value="Illustration-Code:h">Bản fax</option>
 <option value="Illustration-Code:i">coats of arms</option>
 <option value="Illustration-Code:j">Phả hệ</option>
 <option value="Illustration-Code:k">Mẫu</option>
 <option value="Illustration-Code:l">Mẫu</option>
 <option value="Illustration-Code:m">Bản thu âm</option>
 <option value="Illustration-Code:n">Giấy trong</option>
 <option value="Illustration-Code:o">Bản phối mầu</option>
 <option value="Illustration-Code:y">Minh họa khác</option>
 </select>
 </p>
 <p>
 <label>Nội dung</label>
 <select name="limit" class="subtype">
 <option value="" >Tất cả</option>
 <option value="ctype:a" >Tiểu sử</option>
 <option value="ctype:b" >Từ khóa</option>
 <option value="ctype:c" >Chỉ số</option>
 <option value="ctype:d" >Tóm tắt</option>
 <option value="ctype:e" >Từ điển</option>
 <option value="ctype:f" >Bách khoa toàn thư</option>
 <option value="ctype:g" >Thư mục</option>
 <option value="ctype:h" >Mô tả dự án</option>
 <option value="ctype:i" >Thống kê</option>
 <option value="ctype:j" >Sách lập trình</option>
 <option value="ctype:k" >Bằng sáng chế</option>
 <option value="ctype:l" >Tiêu chuẩn</option>
 <option value="ctype:m" >Luận văn, Luận đề</option>
 <option value="ctype:n" >Luật và pháp chế</option>
 <option value="ctype:o" >Bảng số liệu</option>
 <option value="ctype:p" >Báo cáo kỹ thuật</option>
 <option value="ctype:q" >Phiếu điều tra</option>
 <option value="ctype:r" >Khảo sát văn học</option>
 <option value="ctype:s" >Hiệp ước</option>
 <option value="ctype:t" >Thư giãn</option>
 <option value="ctype:v" >Luận văn (Kiểm duyệt)</option>
 <option value="ctype:w" >Tôn giáo</option>
 <option value="ctype:z" >Báo cáo khác</option>
 </select>
 </p>
 <p>
 <label>Kiểu Video</label>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Video-mt:a">Tranh hoạt họa</option>
 <option value="Video-mt:b">Phim chiếu</option>
 <option value="Video-mt:c">Băng ghi hình</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Ấn phẩm định kỳ</legend><p>
 <p>
 <label>Phân loại kiểu Ấn Phẩm</label>
 <select name="limit" class="subtype">
 <option value="">Tất cả các kiểu</option>
 <option value="Type-Of-Serial:a">Định kỳ</option>
 <option value="Type-Of-Serial:b">Chuyên khảo</option>
 <option value="Type-Of-Serial:c">Bài báo</option>
 <option value="Type-Of-Serial:e">Cập nhật từng phần</option>
 <option value="Type-Of-Serial:f">Cơ sở dữ liệu</option>
 <option value="Type-Of-Serial:g">Cập nhật trang Web</option>
 <option value="Type-Of-Serial:z">Báo cáo khác</option>
 </select>
 </p>
 <p>
 <label>Thời gian phát hành</label>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Frequency-code:a">1 số/ngày</option>
 <option value="Frequency-code:b">2 số/tuần</option>
 <option value="Frequency-code:c">1 số/tuần</option>
 <option value="Frequency-code:d">2 tuần/số</option>
 <option value="Frequency-code:e">2 số/tháng</option>
 <option value="Frequency-code:f">1 số/tháng</option>
 <option value="Frequency-code:g">2 tháng/số</option>
 <option value="Frequency-code:h">1 số/quý</option>
 <option value="Frequency-code:i">3 năm/số</option>
 <option value="Frequency-code:j">2 số/năm</option>
 <option value="Frequency-code:k">1 số/năm</option>
 <option value="Frequency-code:l">2 năm/số</option>
 <option value="Frequency-code:m">3 năm/số</option>
 <option value="Frequency-code:n">3 số/tuần</option>
 <option value="Frequency-code:o">3 số/tháng</option>
 <option value="Frequency-code:y">Không cố định</option>
 <option value="Frequency-code:u">Không biết</option>
 <option value="Frequency-code:z">Báo cáo khác</option>
 </select>
 </p>
 <p>
 <label>Quy tắc</label>
 <select name="limit" class="subtype">
 <option value="">Quy tắc bất kỳ</option>
 <option value="Regularity-code:a">Có quy tắc</option>
 <option value="Regularity-code:b">normalised irregular</option>
 <option value="Regularity-code:y">Không qui tắc</option>
 <option value="Regularity-code:u">Không biết</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Ảnh</legend>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Graphics-type:a">Tranh dán</option>
 <option value="Graphics-type:b">Tranh họa tiết</option>
 <option value="Graphics-type:c">Tranh vẽ</option>
 <option value="Graphics-type:d">Tranh sao chép quang cơ</option>
 <option value="Graphics-type:e">Ảnh âm bản</option>
 <option value="Graphics-type:f">Tranh in</option>
 <option value="Graphics-type:h">Ảnh</option>
 <option value="Graphics-type:i">Bản in</option>
 <option value="Graphics-type:k">Bản vẽ kỹ thuật</option>
 <option value="Graphics-type:z">Các thể loại khác</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Graphics-support:a">Vải bạt</option>
 <option value="Graphics-support:b">Giấy cứng</option>
 <option value="Graphics-support:c">Bìa các tông</option>
 <option value="Graphics-support:d">Cỏ</option>
 <option value="Graphics-support:j">Thạch cao</option>
 <option value="Graphics-support:k">Gỗ ép</option>
 <option value="Graphics-support:l">Gốm sứ</option>
 <option value="Graphics-support:m">Đá</option>
 <option value="Graphics-support:n">Gỗ</option>
 <option value="Graphics-support:v">Chất liệu tổng hợp</option>
 <option value="Graphics-support:e">Vật liệu nhân tạo</option>
 <option value="Graphics-support:f">Lụa</option>
 <option value="Graphics-support:g">Vải dệt</option>
 <option value="Graphics-support:h">Kim loại</option>
 <option value="Graphics-support:i">Giấy</option>
 <option value="Graphics-support:z">Vật liệu khác</option>
 <option value="Graphics-support:u">Không biết</option>
 </select>
</fieldset>
