<!-- Authority details modal -->
<div class="modal" id="authorityDetail" tabindex="-1" role="dialog" aria-labelledby="authorityDetailLabel">
 <div class="modal-dialog" role="document">
 <div class="modal-content">
 <div class="modal-header">
 <button aria-label="Thoát" class="closebtn" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
 <h4 class="modal-title" id="authorityDetailLabel"></h4>
 </div>
 <div class="modal-body">
 <img src="[% interface | html %]/[% theme | html %]/img/spinner-small.gif" alt="" />
 </div>
 <div class="modal-footer">
 <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
 </div>
 </div>
 </div>
</div>
