<p>
 <a id="show_coded_fields" class="toggle_element" data-element="#Coded_Fields,#show_coded_fields,#hide_coded_fields" href="#"><i class="fa fa-plus-square-o"></i> Hiện các bộ lọc thông tin mã hóa</a>
 <a id="hide_coded_fields" class="toggle_element" data-element="#Coded_Fields,#show_coded_fields,#hide_coded_fields" href="#" style="display:none;"><i class="fa fa-minus-square-o"></i> Ẩn các bộ lọc thông tin mã hóa</a>
</p>
<div style="display:none;" id="Coded_Fields">
<!-- SUBTYPE LIMITS -->
 <fieldset>
 <legend>Các trường dữ liệu</legend>
 <p>
 <label for="audience">Bạn đọc: </label>
 <select id="audience" name="limit" class="subtype">
 <option value="" selected="selected" >Tất cả</option>
 <option value="ta:a">Vị thành niên</option>
 <option value="ta:b">Sách cho trẻ từ(0-5)</option>
 <option value="ta:c">Sách cho trẻ từ (5-8)</option>
 <option value="ta:d">Sách cho trẻ từ(9-14)</option>
 <option value="ta:e">Vị thành niên</option>
 <option value="ta:k">Sách cho người lớn</option>
 <option value="ta:m">Sách cho người lớn nói chung</option>
 <option value="ta:u">Không biết</option>
 </select>
 </p>
 <p>
 <label for="physical_presentation">Mô tả vật lý:</label>
 <select id="physical_presentation" name="limit" class="subtype">
 <option value="" selected="selected" >Tất cả</option>
 <option value="ff8-23:r">In thường</option>
 <option value="ff8-23:d">In khổ lớn</option>
 <option value="ff8-23:e">Định dạng báo</option>
 <option value="ff8-23:f">Sách chữ nổi Braille và bản khắc</option>
 <option value="ff8-23:g">micro phim</option>
 <option value="ff8-23:h">Bản thảo viết tay</option>
 <option value="ff8-23:i">Tài liệu nghe nhìn</option>
 <option value="ff8-23:j">mini-print</option>
 <option value="ff8-23:s">Electronic resource</option>
 <option value="ff8-23:t">micro phim</option>
 <option value="ff8-23:z">Loại khác</option>
 </select>
 </p>
 <p>
 <label for="literary_genre">Loại sách: </label>
 <select id="literary_genre" name="limit" class="subtype">
 <option value="" selected="selected" >Tất cả</option>
 <option value="lf:a">Viễn tưởng</option>
 <option value="lf:b">Kịch</option>
 <option value="lf:c">Tiểu luận</option>
 <option value="lf:d">Tryện cười</option>
 <option value="lf:e">Văn học</option>
 <option value="lf:f">Truyện ngắn</option>
 <option value="lf:g">Thơ</option>
 <option value="lf:h">Diễn văn, biện luận</option>
 <option value="lf:i">Thể loại nhạc kịch</option>
 <option value="lf:y">Các thể loại khác</option>
 <option value="lf:z">Các thể loại hình thức văn học</option>
 </select>
 </p>
 <p>
 <label for="biography">Tiểu sử:</label>
 <select id="biography" name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="bio:y">Không phải tiểu sử</option>
 <option value="bio:a">Tự truyện</option>
 <option value="bio:b">Tiểu sử cá nhân</option>
 <option value="bio:c">Bộ tiểu sử</option>
 <option value="bio:d">Dữ liệu tiểu sử</option>
 </select>
 </p>
 <p>
 <label for="illustration">Minh họa: </label>
 <select id="illustration" name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="ff8-18-21:a">Minh họa</option>
 <option value="ff8-18-21:b">Bản đồ</option>
 <option value="ff8-18-21:c">Chân dung</option>
 <option value="ff8-18-21:d">Biểu đồ</option>
 <option value="ff8-18-21:e">Sơ đồ</option>
 <option value="ff8-18-21:f">Điêu khắc</option>
 <option value="ff8-18-21:g">Âm nhạc</option>
 <option value="ff8-18-21:h">Bản fax</option>
 <option value="ff8-18-21:i">coats of arms</option>
 <option value="ff8-18-21:j">Phả hệ</option>
 <option value="ff8-18-21:k">Mẫu</option>
 <option value="ff8-18-21:l">Mẫu</option>
 <option value="ff8-18-21:m">Bản thu âm</option>
 <option value="ff8-18-21:n">Giấy trong</option>
 <option value="ff8-18-21:o">Bản phối mầu</option>
 <option value="ff8-18-21:y">Minh họa khác</option>
 </select>
 </p>
 <p>
 <label for="content">Nội dung </label>
 <select id="content" name="limit" class="subtype">
 <option value="" >Tất cả</option>
 <option value="ctype:a" >Tiểu sử</option>
 <option value="ctype:b" >Từ khóa</option>
 <option value="ctype:c" >Chỉ số</option>
 <option value="ctype:d" >Tóm tắt</option>
 <option value="ctype:e" >Từ điển</option>
 <option value="ctype:f" >Bách khoa toàn thư</option>
 <option value="ctype:g" >Thư mục</option>
 <option value="ctype:h" >Mô tả dự án</option>
 <option value="ctype:i" >Thống kê</option>
 <option value="ctype:j" >Sách lập trình</option>
 <option value="ctype:k" >Bằng sáng chế</option>
 <option value="ctype:l" >Tiêu chuẩn</option>
 <option value="ctype:m" >Luận văn, Luận đề</option>
 <option value="ctype:n" >Luật và pháp chế</option>
 <option value="ctype:o" >Bảng số liệu</option>
 <option value="ctype:p" >Báo cáo kỹ thuật</option>
 <option value="ctype:q" >Phiếu điều tra</option>
 <option value="ctype:r" >Khảo sát văn học</option>
 <option value="ctype:s" >Hiệp ước</option>
 <option value="ctype:t" >Thư giãn</option>
 <option value="ctype:v" >Luận văn (Kiểm duyệt)</option>
 <option value="ctype:w" >Tôn giáo</option>
 <option value="ctype:z" >Báo cáo khác</option>
 </select>
 </p>
 <p>
 <label for="video_types">Kiểu Video: </label>
 <select id="video_types" name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Video-mt:a">Tranh hoạt họa</option>
 <option value="Video-mt:b">Phim chiếu</option>
 <option value="Video-mt:c">Băng ghi hình</option>
 </select>
 </p>
 </fieldset>

 <fieldset>
 <legend>Ấn phẩm định kỳ</legend>
 <p>
 <label for="serial_type">Loại tài liệu</label>
 <select id="serial_type" name="limit" class="subtype">
 <option value="">Tất cả các kiểu</option>
 <option value="ff8-21:a">Định kỳ</option>
 <option value="ff8-21:b">Chuyên khảo</option>
 <option value="ff8-21:c">Bài báo</option>
 <option value="ff8-21:e">Cập nhật từng phần</option>
 <option value="ff8-21:f">Cơ sở dữ liệu</option>
 <option value="ff8-21:g">Cập nhật trang Web</option>
 <option value="ff8-21:z">Báo cáo khác</option>
 </select>
 </p>
 <p>
 <label for="periodicity">Thời gian phát hành:</label>
 <select id="periodicity" name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="ff8-18:a">1 số/ngày</option>
 <option value="ff8-18:b">2 số/tuần</option>
 <option value="ff8-18:c">1 số/tuần</option>
 <option value="ff8-18:d">2 tuần/số</option>
 <option value="ff8-18:e">2 số/tháng</option>
 <option value="ff8-18:f">1 số/tháng</option>
 <option value="ff8-18:g">2 tháng/số</option>
 <option value="ff8-18:h">1 số/quý</option>
 <option value="ff8-18:i">3 năm/số</option>
 <option value="ff8-18:j">2 số/năm</option>
 <option value="ff8-18:k">1 số/năm</option>
 <option value="ff8-18:l">2 năm/số</option>
 <option value="ff8-18:m">3 năm/số</option>
 <option value="ff8-18:n">3 số/tuần</option>
 <option value="ff8-18:o">3 số/tháng</option>
 <option value="ff8-18:y">Không cố định</option>
 <option value="ff8-18:u">Không biết</option>
 <option value="ff8-18:z">Báo cáo khác</option>
 </select>
 </p>
 <p>
 <label for="regularity">Quy tắc:</label>
 <select id="regularity" name="limit" class="subtype">
 <option value="">Quy tắc bất kỳ</option>
 <option value="ff8-19:a">Có quy tắc</option>
 <option value="ff8-19:b">normalised irregular</option>
 <option value="ff8-19:y">Không qui tắc</option>
 <option value="ff8-19:u">Không biết</option>
 </select>
 </p>
 </fieldset>

 <fieldset>
 <legend>Ảnh</legend>
 <p>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Graphics-type:a">Tranh dán</option>
 <option value="Graphics-type:b">Tranh họa tiết</option>
 <option value="Graphics-type:c">Tranh vẽ</option>
 <option value="Graphics-type:d">Tranh sao chép quang cơ</option>
 <option value="Graphics-type:e">Ảnh âm bản</option>
 <option value="Graphics-type:f">Tranh in</option>
 <option value="Graphics-type:h">Ảnh</option>
 <option value="Graphics-type:i">Bản in</option>
 <option value="Graphics-type:k">Bản vẽ kỹ thuật</option>
 <option value="Graphics-type:z">Các thể loại khác</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Tất cả</option>
 <option value="Graphics-support:a">Vải bạt</option>
 <option value="Graphics-support:b">Giấy cứng</option>
 <option value="Graphics-support:c">Bìa các tông</option>
 <option value="Graphics-support:d">Cỏ</option>
 <option value="Graphics-support:j">Thạch cao</option>
 <option value="Graphics-support:k">Gỗ ép</option>
 <option value="Graphics-support:l">Gốm sứ</option>
 <option value="Graphics-support:m">Đá</option>
 <option value="Graphics-support:n">Gỗ</option>
 <option value="Graphics-support:v">Chất liệu tổng hợp</option>
 <option value="Graphics-support:e">Vật liệu nhân tạo</option>
 <option value="Graphics-support:f">Lụa</option>
 <option value="Graphics-support:g">Vải dệt</option>
 <option value="Graphics-support:h">Kim loại</option>
 <option value="Graphics-support:i">Giấy</option>
 <option value="Graphics-support:z">Vật liệu khác</option>
 <option value="Graphics-support:u">Không biết</option>
 </select>
 </p>
</fieldset>
</div>
